[package]
name = "bevy_pong"
version = "0.1.0"
edition = "2021"
authors = ["nfoj <nfoj_@hotmail.com>"]

[dependencies]
bevy = "0.15"
bevy_rapier2d = "0.28"
bevy_egui = "0.31"
leafwing-input-manager = "0.16"
