[package]
name = "bevy_pong"
version = "0.1.0"
edition = "2021"
authors = ["nfoj <nfoj_@hotmail.com>"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.31"
bevy_rapier2d = "0.28.0"
leafwing-input-manager = "0.16"
